services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend-api
  backend-api:
    build: ./backend-api
    ports:
      - "8080:8000"
    depends_on:
      - db
      - face-recognition-api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/attendance
      - FACE_API_URL=http://face-recognition-api:8001
  face-recognition-api:
    build: ./face-recognition-api
    ports:
      - "8081:8001"
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 